version: '3.8'
services:
  bot:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    command: bash -lc "pip install -r requirements.txt && python main.py"
